### Create new product
POST https://dkp298o56i.execute-api.ap-south-1.amazonaws.com/dev/products/
Content-Type: application/json
x-api-Key: r1J23lGqOn2Uw3K1BOG8h1fzKo6OAO5g5hY8P41n

{
  "name": "Pepero biscuits",
  "description": "Chocolate coated biscuit sticks",
  "price": 34,
  "imageUrl": "https://plerion-project-inventory-image-bucket.s3.ap-south-1.amazonaws.com/DSC01023.JPG"
}

### Get all products

GET https://dkp298o56i.execute-api.ap-south-1.amazonaws.com/dev/products?page=1&limit=10
Content-Type: application/json
X-API-Key: r1J23lGqOn2Uw3K1BOG8h1fzKo6OAO5g5hY8P41n


### Get a products

GET https://dkp298o56i.execute-api.ap-south-1.amazonaws.com/dev/products/c036805c-b1dc-47c3-a434-1f7277c15225
Content-Type: application/json
X-API-Key: r1J23lGqOn2Uw3K1BOG8h1fzKo6OAO5g5hY8P41n


### Delete a product

DELETE https://dkp298o56i.execute-api.ap-south-1.amazonaws.com/dev/products/c036805c-b1dc-47c3-a434-1f7277c15225
Content-Type: application/json
X-API-Key: r1J23lGqOn2Uw3K1BOG8h1fzKo6OAO5g5hY8P41n